[package]
name = "krasavchik"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"

[dependencies.mongodb]
version = "2.6.1"
features = ["tokio-sync"]
